- name: configure payment component
  hosts: payment
  become: true
  tasks:
  - name: install Python3 packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel

  - name: Create a roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download payment code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

   # This module by default feels like the file exists on the ansible control server, needs to extract on to remote machine
  - name: Extract the payment code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: true   # remote_src means the file is already available in the catalogue server

  - name: Install dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy payment service
    ansible.builtin.copy:
      src: payment_service
      dest: /etc/systemd/system/payment.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: true

  
