- name: configure user component
  hosts: user
  become: true
  tasks:
  - name: disable default modejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable modejs:20 module
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install modejs:20 module
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: Create a roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  
  - name: create an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Donwload user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip


   # This module by default feels like the file exists on the ansible control server, needs to extract on to remote machine
  - name: Extract the user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: true   # remote_src means the file is already available in the user server

  - name: Install dependencies
    community.general.npm:
      path: /app 

  - name: copy the user service to system directory
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: true

 